config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'tasks#index'

  resources :users, only: [:show]

  resources :tasks

  resource :profile

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :avatar
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  has_many :todocontents
  accepts_nested_attributes_for :todocontents, reject_if: :all_blank, allow_destroy: true
end

app/models/todocontent.rb
class Todocontent < ApplicationRecord
  belongs_to :todo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :todos, dependent: :destroy
  require 'date'

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = current_user.profile
    @tasks = current_user.tasks
  end

  def edit
    # if current_user.profile.present?
    #   @profile = current_user.profile
    # else
    #   @profile = current_user.build_profile
    # end
    @profile = current_user.profile || current_user.build_profile
  end

  def update
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
    
  end

  private
  
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :enrollment_date,
      :target,
      :theme,
      :avatar
    )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
      @tasks = Task.all
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task), notice: '今日もお疲れ様でした^^'
    else
      flash_now[:error] = 'まだ書いてない項目があるよ'
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task), notice: '更新できました，'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy!
    redirect_to root_path, notice: '記事を削除しました，'
  end

  private
    def task_params
        params.require(:task).permit(
          :exihibits,
          :solds,
          :sale,
          :profit,
          :impress
        )
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = current_user.todos.build
  end

  def create
    @todo = current_user.todos.build(todo_params)
    if @todo.save
      redirect_to todo_path(@todo), notice: '今日も楽しんで行こう'
    else
      flash_now[:error] = 'まだ書いてない項目があるよ'
      render :new
    end
  end

  def edit
  end

  def update

  end

  private
  def todo_params
    params.require(:todo).permit(
      :date_of,
      todocontents_attributes: [:id, :todo, :completed]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @profile = user.profile 
    @tasks = user.tasks
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title DaiyajukuTaskApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
      = link_to(root_path) do
        %p.header_pageTitle ダイヤ塾TaskApp
      - if user_signed_in?
        .dropdown
          = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: {method: 'delete'}
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |m|
      %li= m
  .task-form
    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
      %div
        = f.label :avatar, 'プロフィール画像'
      %div
        = f.file_field :avatar
      %div
        = f.label :nickname, 'ニックネーム'
      %div
        = f.text_field :nickname
      %div
        = f.label :enrollment_date, 'ダイヤ塾入会日'
      %div
        = f.date_field :enrollment_date, value: (f.object.enrollment_date || Time.now.strftime("%Y-%m-%d"))
      %div
        = f.label :target, '目標月利'
      .count
        = f.number_field :target
        %p 円
      %div
        = f.label :theme, 'ダイヤ塾で達成したいこと'
      %div
        = f.text_area :theme
      = f.submit '更新', class: 'btn btn-primary'

app/views/profiles/show.html.haml
.UserProfile
  -if @profile&.avatar&.attached?
    = image_tag @profile.avatar, class: 'UserProfile-Avatar'
  -else
    =image_tag 'default-avatar.png', class: 'UserProfile-Avatar'
  .UserProfile-Edit
    = link_to 'Edit Profile', edit_profile_path, class: 'UserProfile-Edit-Ji'
  .UserProfile-Content
    %p.UserProfile-Content-Name= @profile.nickname
    %p.UserProfile-Content-Date= @profile.enrollment_date
    .UserProfile-Content-Target
      %p.UserProfile-Content-Target-Ji 目標金額
      %p.UserProfile-Content-Target-Kane
        = @profile.target
        万円
    %p.UserProfile-Content-Theme= @profile.theme
- @tasks.each do |task|
  .card
    .card-head
      = image_tag 'default-avatar.png', class: 'card_icon'
      %p.card-head-name= task.user.username
      %p.card-head-day
        = task.created_at.month
        &frasl;
        = task.created_at.day
      の成果
    .card-body
      .card-body-nippou
        %table.table
          %tbody
            %tr
              %th 出品数
              %td.number= task.exihibits
              %td.unit 個
            %tr
              %th 販売個数
              %td.number= task.solds
              %td.unit 個
            %tr
              %th 売り上げ
              %td.number= task.sale
              %td.unit 円
            %tr
              %th 利益
              %td.number= task.profit
              %td.unit 円
            %tr
              %th 振り返り
              %td.impress{:colspan => '2'}= task.impress
      .card-body-react
        %svg.bi.bi-chat{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z", "fill-rule" => "evenodd"}
        %svg.bi.bi-heart{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z", "fill-rule" => "evenodd"}

app/views/tasks/_form.html.haml
.container
  - task.errors.full_messages.each do |m|
    %li= m
  .task-form
    = form_with(model: task, local: true) do |f|
      %div
        = f.label :exihibits
      .count
        = f.number_field :exihibits
        %p 個
      %div
        = f.label :solds
      .count
        = f.number_field :solds
        %p 個
      %div
        = f.label :sale
      .count
        = f.number_field :sale
        %p 円
      %div
        = f.label :profit
      .count
        = f.number_field :profit
        %p 円
      %div
        = f.label :impress
      %div
        = f.text_area :impress, class: 'text'
      = f.submit '更新', class: 'btn btn-primary'

app/views/tasks/edit.html.haml
%h1 日報編集
= render 'form', task: @task

app/views/tasks/index.html.haml
- @tasks.each do |task|
  = link_to task_path(task) do
    .card
      .card-head
        %object
          = link_to user_path(id: task.user.id) do
            = image_tag 'default-avatar.png', class: 'card_icon'
        %p.card-head-name= task.user.username
        %p.card-head-day
          = task.created_at.month
          &frasl;
          = task.created_at.day
        の成果
      .card-body
        .card-body-nippou
          %table.table
            %tbody
              %tr
                %th 出品数
                %td.number= task.exihibits
                %td.unit 個
              %tr
                %th 販売個数
                %td.number= task.solds
                %td.unit 個
              %tr
                %th 売り上げ
                %td.number= task.sale
                %td.unit 円
              %tr
                %th 利益
                %td.number= task.profit
                %td.unit 円
              %tr
                %th 振り返り
                %td.impress{:colspan => '2'}= task.impress
        .card-body-react
          %svg.bi.bi-chat{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z", "fill-rule" => "evenodd"}
          %svg.bi.bi-heart{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z", "fill-rule" => "evenodd"}
=link_to new_task_path do
  .float-btn
    %svg.bi.bi-plus-circle-fill{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
      %path{:d => "M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4a.5.5 0 0 0-1 0v3.5H4a.5.5 0 0 0 0 1h3.5V12a.5.5 0 0 0 1 0V8.5H12a.5.5 0 0 0 0-1H8.5V4z", "fill-rule" => "evenodd"}

app/views/tasks/new.html.haml
%h1 日報提出画面
= render 'form', task: @task

app/views/tasks/show.html.haml
.card
  .card-head
    = image_tag 'default-avatar.png', class: 'card_icon'
    %p.card-head-name= @task.user.username
    %p.card-head-day
      = @task.created_at.month
      &frasl;
      = @task.created_at.day
    の成果
  .card-body
    .card-body-nippou
      %table.table
        %tbody
          %tr
            %th 出品数
            %td.number= @task.exihibits
            %td.unit 個
          %tr
            %th 販売個数
            %td.number= @task.solds
            %td.unit 個
          %tr
            %th 売り上げ
            %td.number= @task.sale
            %td.unit 円
          %tr
            %th 利益
            %td.number= @task.profit
            %td.unit 円
          %tr
            %th 振り返り
            %td.impress{:colspan => '2'}= @task.impress
    .card-body-react
      %svg.bi.bi-chat{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z", "fill-rule" => "evenodd"}
      %svg.bi.bi-heart{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z", "fill-rule" => "evenodd"}

app/views/todos/_todocontent_fields.html.haml
.nested-fields
  .field
    = f.label :todo
    = f.text_field :todo
    = link_to_remove_association 'Remove ToDo', f

app/views/todos/new.html.haml
.container
  - @todo.errors.full_messages.each do |m|
    %li= m
  .todo-form
    = form_with(model:@todo, url: todos_path, method: 'post', local: true) do |f|
      %div
        = f.label '日にち', :date_of
      .count
        = f.date_field :date_of
        %p のToDoリスト
      = f.fields_for :todocontents do |ff|
        = render 'todocontent_fields', f: ff
      .links
        = link_to_add_association 'Add ToDo.', f, :todocontents
      = f.submit '更新', class: 'btn btn-primary'

app/views/users/show.html.haml
.UserProfile
  -if @profile&.avatar&.attached?
    = image_tag @profile.avatar, class: 'UserProfile-Avatar'
  -else
    =image_tag 'default-avatar.png', class: 'UserProfile-Avatar'
  .UserProfile-Content
    %p.UserProfile-Content-Name= @profile.nickname
    %p.UserProfile-Content-Date= @profile.enrollment_date
    .UserProfile-Content-Target
      %p.UserProfile-Content-Target-Ji 目標金額
      %p.UserProfile-Content-Target-Kane
        = @profile.target
        万円
    %p.UserProfile-Content-Theme= @profile.theme
- @tasks.each do |task|
  .card
    .card-head
      = image_tag 'default-avatar.png', class: 'card_icon'
      %p.card-head-name= task.user.username
      %p.card-head-day
        = task.created_at.month
        &frasl;
        = task.created_at.day
      の成果
    .card-body
      .card-body-nippou
        %table.table
          %tbody
            %tr
              %th 出品数
              %td.number= task.exihibits
              %td.unit 個
            %tr
              %th 販売個数
              %td.number= task.solds
              %td.unit 個
            %tr
              %th 売り上げ
              %td.number= task.sale
              %td.unit 円
            %tr
              %th 利益
              %td.number= task.profit
              %td.unit 円
            %tr
              %th 振り返り
              %td.impress{:colspan => '2'}= task.impress
      .card-body-react
        %svg.bi.bi-chat{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z", "fill-rule" => "evenodd"}
        %svg.bi.bi-heart{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z", "fill-rule" => "evenodd"}
=link_to new_task_path do
  .float-btn
    %svg.bi.bi-plus-circle-fill{:fill => "currentColor", :height => "1em", :viewbox => "0 0 16 16", :width => "1em", :xmlns => "http://www.w3.org/2000/svg"}
      %path{:d => "M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4a.5.5 0 0 0-1 0v3.5H4a.5.5 0 0 0 0 1h3.5V12a.5.5 0 0 0 1 0V8.5H12a.5.5 0 0 0 0-1H8.5V4z", "fill-rule" => "evenodd"}